variable "resource_group_name" {}
variable "resource_group_region" {}
variable "server_app_service_plan_name" {}
variable "server_app_service_sku_tier" {}
variable "server_app_service_name" {}
variable "server_app_service_size" {}
variable "always_on" {}
variable "use_32_bit_process" {}
variable "server_container_name" {}
variable "container_registry_name" {}
variable "container_registry_password" {}
